services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    image: 'wolveix/satisfactory-server'
    ports:
      - '7777:7777/tcp'
      - '7777:7777/udp'
      - '8888:8888/tcp'
    volumes:
      - './data:/config'
    environment:
      - MAXPLAYERS=3
    restart: unless-stopped